spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
org:
  slf4j:
  simpleLogger:
    logFile: System.out
    defaultLogLevel: debug
    showShortLogName: true
    log:
      org:
        apache:
          kafka: warn
telemetry:
  analyzer:
    kafka:
      properties:
        bootstrap.servers: localhost:9092
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        enable.auto.commit: false
      consumers:
        - type: SnapshotProcessor
          properties:
            value.deserializer: org.apache.kafka.common.serialization.SensorsSnapshotDeserializer
            group.id: telemetry.analyzer.snapshot
          topics:
            - telemetry.snapshots.v1
          poll-timeout: 500
        - type: HubEventProcessor
          properties:
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group.id: telemetry.analyzer.hub
          topics:
              - telemetry.hubs.v1
          poll-timeout: 2000
