spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
org:
  slf4j:
  simpleLogger:
    logFile: System.out
    defaultLogLevel: debug
    showShortLogName: true
    log:
      org:
        apache:
          kafka: warn
telemetry:
  analyzer:
    kafka:
      server: localhost:9092
      hub:
        topic: telemetry.hubs.v1
      sensor:
        topic: telemetry.sensors.v1
      snapshot:
        topic: telemetry.snapshots.v1
