server:
  port: 8082
grpc:
  server:
    port: 59091
org:
  slf4j:
  simpleLogger:
    logFile: System.out
    defaultLogLevel: debug
    showShortLogName: true
    log:
      org:
        apache:
          kafka: warn
telemetry:
  collector:
    kafka:
      server: localhost:9092
      hub:
        topic: telemetry.hubs.v1
      sensor:
        topic: telemetry.sensors.v1
